# Generated by Django 5.0.6 on 2024-07-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=200)),
                ('fullname', models.CharField(max_length=200)),
                ('logindt', models.CharField(max_length=200)),
                ('validdt', models.CharField(max_length=55)),
                ('permission', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('set_date', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('personal_id', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Craftsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('set_date', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('personal_id', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('last_login', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=210)),
                ('salary', models.CharField(max_length=200)),
                ('visit_salary', models.CharField(max_length=200)),
                ('descript', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='dbImages')),
            ],
        ),
    ]
